### ISSUE TITLE
Add arm64 build in open store

### ISSUE THREAD

**Issue by henri2h** [Arc676/xkcd-Viewer#14]
Just tried compiling the app for arm64 and it works great !!
clickable --arch arm64

Maybe arm64 packages could be added to the store ?
Nerveless, thanks for this great app !! Love seeing xkcd comics on my ubuntu phone again !! :)

**Comment by Arc676** [comment]
Thank you for the feedback! When I first published the xkcd Viewer, it was not possible to publish for multiple architectures. I saw that this is now possible, so I can definitely add an arm64 build soon.

**Comment by Arc676** [comment]
Sorry for the long wait! I've uploaded a new version of the XKCD viewer to the OpenStore. The app should now be available for both amd64 and armhf. However I don't have an amd64 UT device. Would you mind confirming that it works?

**Comment by henri2h** [comment]
Afraid, I cannot find it in the store.

**Comment by Arc676** [comment]
Huh. That's weird. If I view the page on desktop it clearly offers both amd64 and armhf downloads and both architectures are listed as available in the app details. What device are you using and on what version of UT?

**Comment by henri2h** [comment]
Strange, I don't see it in the store when using my UT device.
I use UT on Xperia X. Version Ubuntu 16.04 (2020-03-25/2) from the 16.04/arm64/edge branch.

**Comment by Arc676** [comment]
I don't understand; do you mean that you could or couldn't see it in the store? Perhaps you meant that you could see it in a web browser but not in the OpenStore app itself?

**Comment by henri2h** [comment]
Oh sorry, yes, that's right
![screenshot20200512_002642459](https://user-images.githubusercontent.com/13080562/81618323-62a60f80-93e7-11ea-9212-0fb965ad08a0.png)

**Comment by Arc676** [comment]
Ok turns out I'm just an idiot and built for `amd64` instead of `arm64` and somehow never noticed that it wasn't the right architecture. I have now uploaded the correct build. Sorry for the inconvenience.

**Comment by henri2h** [comment]
thanks !! App sucsuccessfully installed. Looks like it doesn't noticed it also 😃
